### ISSUE TITLE
All actions blocked on Instapy (Raspberry Pi 3), BUT working on my phone

### ISSUE THREAD

**Issue by bjspi** [InstaPy/InstaPy#4676]
I have a simple Instapy script which likes pictures by Hashtag and tries to follow 20% of those users. The script runs on a raspberry Pi 3. Liking and commenting pictures still works, but following doesnt anymore. It always says "Phew, couldnt verify the follow. Maybe you are blocked". **EDIT**: Liking and commenting doesnt work either anymore. 

This script ran for a while but unfortunately it stopped working suddenly a few days ago.

On my phone following still works, even when Im using the same WiFi to connect to Instagram.

I tried to delete the Instapy stored cookie (MYACCOUNT_cookie.pkl) and it worked again for one script-run, but not anymore afterwards.

My Instapy Version is 0.4.2. I dont dare to update as I know from initially setting up everything that getting things to work on a Raspberry Pi 3 with the dependency on Chromedriver was a bit cumbersome. But in the changed codebase it doesnt seem as if the latest Instapy version changed something w.r.t. Following users.

Is there anything I can do?
What are you ideas?

Thanks!

### **EDIT EDIT EDIT**
**See below for my temporary solution which seems to work fine for me as of now (changing Chromium settings)**

**Comment by angezanetti** [comment]
I got the same issue !

**Comment by bjspi** [comment]
Do you also use version 0.4.4 or do you even use latest version 0.5.x something?
Because if you are using the latest 0.5.x than I dont even need to try updating to it..

Is there any way to delete Chromium/Chromedriver cache or so, so that instagram doesnt detect me again? Maybe they block the same browser over and over again?

**Comment by angezanetti** [comment]
I'm running the last version: `0.5.4`

**Comment by andifds** [comment]
I'm getting  the same! I think it relates to cache and cookies. Don't know how to flush them. If anyone got an idea ...

**Comment by bjspi** [comment]
@angezanetti Thanks for the info, so as I thought by comparing the codebase, it's got nothing to do with my older version 0.4.4. So no need to try updating as of now if you got the same problems.

Are your problems also solved temporarly when deleting the cookie?

@andifds Yes thought the same. When I once deleted the cookie it worked once again. Ill try again to verify. Unfortunately I dont have a clue how to clear/delete the whole cache, or even better how to change chrome/chromedriver to delete all cache/cookies etc when closing it. As Im running Raspberry in the terminal without GUI wondering how to do it on commandline.

**Comment by bjspi** [comment]
I modified the Chromium settings (I suspect Chromium is used by Chromedriver in the background ;-)) and it seems everything is working fine again, even when Instapy adds my User-Cookie to Chromium while running...

`sudo nano /etc/chromium-browser/default`

Than change the settings to:

`CHROMIUM_FLAGS="--incognito --disk-cache-dir=/dev/null --disk-cache-size=1"`


If it doesnt work for you, you could change the Instapy code slightly to not load the user cookie at all, so that Instapy would login again everytime the Bot runs. In the file instapy/login_util.py you would just need to comment out the following line:
`browser.add_cookie(cookie)`

So it would never use the cookie.pkl file.

**Comment by aranwilcox** [comment]
I edited the login_util.py file and commented out the line below:
browser.add_cookie(cookie)

This worked for me for about 3 minutes and then I got blocked again :(.

**Comment by bjspi** [comment]
Does it work for you to change the config of Chromium?

**Comment by Good-Kat** [comment]
I edited the login_util.py file and commented out the line below:
browser.add_cookie(cookie)

I did the same and removed cookie. Still working. Around a hour or so

**Comment by e1x4** [comment]
with #browser.add_cookie(cookie) 

now it works for me all the day

**Comment by bjspi** [comment]
@e1x4 & @Good-Kat 
Glad it worked for you.
Maybe you should try to change Chromium config instead if it helps you as well. It's a better solution when it comes to updating instapy in future

@aranwilcox 
Changing this line in the code will only work in case manually deleting the pkl file (the stored cookie in the instapy folder) works. For me, whenever I manually deleted the cookie file to force instapy to login fresh, it worked for one session of the bot. As I didn't want to delete the file every time I commented this line of code which in fact will have the same outcome: no cookie loaded hence fresh login required.

Sorry to hear it doesn't work for you but very strange to hear that so many have trouble right now with using the stored cookie from session to session.

**Comment by bjspi** [comment]
@e1x4 & @Good-Kat 
Glad it worked for you.
Maybe you should try to chance Chromium config instead if it helps you as well. It's a better solution when it comes to updating instapy in future

@aranwilcox 
Changing this line in the code will only work in case manually deleting the pkl file (the stored cookie in the instapy folder) works. For me, whenever I manually deleted the cookie file to force instapy to login fresh, it worked for one session of the bot. As I didn't want to delete the file every time I commented this line of code which in fact will have the same outcome: no cookie loaded hence fresh login required.

Sorry to hear it doesn't work for you but very strange to hear that so many have trouble right now with using the stored cookie from session to session.

**Comment by e1x4** [comment]
> 
> 
> @e1x4 & @Good-Kat
> Glad it worked for you.
> Maybe you should try to change Chromium config instead if it helps you as well. It's a better solution when it comes to updating instapy in future
> 

I forgot to say I am on windows...so I can't use those commands: sudo nano /etc/chromium-browser/default

anyway now I have put again browser.add_cookie(cookie) and it works...

**Comment by bjspi** [comment]
@e1x4
No worries, but I'm pretty sure there's also a way to change the way Chrome behaves when initiated by chromedriver, so that it doesn't store cookies and cache or deletes it on closure. 

Otherwise you could also remove the cookie pkl file by your python script at the end of runtime.


@timgrossmann could you please check why do many people have trouble right now with the storage and usage of the login cookie? Thanks

**Comment by Tachenz** [comment]
@e1x4 @Good-Kat @bjspi how long are your sessions and at what speed (liking/following) are you going?

**Comment by Tachenz** [comment]
This is so weird. I commented out add cookie line, but cookie gets created every time still :)

**Comment by bjspi** [comment]
Yes thats the expected behaviour, but it will not get loaded during startup of the session. If you want to make absolutely sure you can also comment out the line where it gets stored to disk. Which would be this line:

```
# create cookie for username

 pickle.dump(browser.get_cookies(), open(
            '{0}{1}_cookie.pkl'.format(logfolder, username), 'wb'))
```

**Comment by e1x4** [comment]
after 3 days that worked well the problem recurred today, ok I have I commented out the cookie line, now it's ok. 

Edit: just 1 hour runtime and action blocked again :(

**Comment by e1x4** [comment]
> 
> 
> @e1x4 @Good-Kat @bjspi how long are your sessions and at what speed (liking/following) are you going?

it worked for 3 days, now again the same issue...my speed was only following, about 10 followers every 10 minutes

**Comment by bjspi** [comment]
Oh my gosh, I think developers should step in here, as so many of us have problems here. I really don't have a clue maybe Instagram can detect in the meantime the bot

**Comment by e1x4** [comment]
> 
> 
> Oh my gosh, I think developers should step in here, as so many of us have problems here. I really don't have a clue maybe Instagram can detect in the meantime the bot

Maybe detect chromium drivers?

**Comment by KMLnk** [comment]
> > Oh my gosh, I think developers should step in here, as so many of us have problems here. I really don't have a clue maybe Instagram can detect in the meantime the bot
> 
> Maybe detect chromium drivers?

yes, chrome driver detect by insta server

**Comment by KMLnk** [comment]
I want instapy setup firefox with this code. add this line in browser.py file
`        browser = webdriver.Firefox(firefox_profile=firefox_profile,executable_path='.\\assets\\geckodriver.exe',
                                    options=firefox_options)`

**Comment by bjspi** [comment]
> > > Oh my gosh, I think developers should step in here, as so many of us have problems here. I really don't have a clue maybe Instagram can detect in the meantime the bot
> > 
> > 
> > Maybe detect chromium drivers?
> 
> yes, chrome driver detect by insta server

I was thinking about it as well, but dont think so.
Just think about it: You gotta have Chrome/Chromium installed which is just controlled by chromedriver, i.e. chromedriver just takes care of controlling the mouse and the keyboard (scrolling the page, clicking buttons or links, "typing" letters into fields), nothing else. So instagram just sees that Chrome visits the page, nothing else. 

@uluQulu Could you maybe check why so many people have problems here? Thanks

**Comment by e1x4** [comment]
well I tried with firefox, with my account, the same thing, so I tried with my app and the same, so it's a instagram block about my account today...ok I'll wait one day without following

**Comment by bjspi** [comment]
I think you better wait a week or so :)

**Comment by xuhig** [comment]
add random user agent fix this problem?

**Comment by bjspi** [comment]
You could try yourself like this and see whether it fixes the prob:
https://stackoverflow.com/a/49565080/701049

**Comment by JoeFertig** [comment]
Guys you need to be patient. 
The team is developing some new stuff so hopefully this IG mess will get fixed soon ;)

**Comment by bjspi** [comment]
This is a major fix which should be supplied faster than ALL new features.
Thats usually how you go about major problems which affect so many users and make the whole tool un-usable. :)

**Comment by Tachenz** [comment]
@JoeFertig Awesome news! I thought everyone has given up on it :D

**Comment by Tachenz** [comment]
@JoeFertig Awesome news! I thought everyone has given up on it :D

**Comment by tourhuntr** [comment]
Does not work for me, deleted cookie, commented out this
#create cookie for username

 pickle.dump(browser.get_cookies(), open(
            '{0}{1}_cookie.pkl'.format(logfolder, username), 'wb'))

and that

#browser.add_cookie(cookie)

modified the 

sudo nano /etc/chromium-browser/default

#Default settings for chromium-browser. This file is sourced by /bin/sh from
#/usr/bin/chromium-browser
CHROMIUM_FLAGS="--incognito --disk-cache-dir=/dev/null --disk-cache-size=1"


but instapy wants to load the cookie and then wants to create some...

this is the error message i get:

Traceback (most recent call last):
  File "good_commenting_strategy_and_new_qs_system.py", line 38, in <module>
    with smart_run(session):
  File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/pi/projects/InstaPy/instapy/util.py", line 1662, in smart_run
    session.login()
  File "/home/pi/projects/InstaPy/instapy/instapy.py", line 373, in login
    self.bypass_with_mobile):
  File "/home/pi/projects/InstaPy/instapy/login_util.py", line 262, in login_user
    "//button[text()='Log in']")
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[text()='Log in']"}
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.79-v7+ armv7l)

**Comment by JoeFertig** [comment]
No we won't give up ;)
I hope the new update will make Raspberry users life easier :)

**Comment by andreescocard** [comment]
Same problem here

**Comment by iam4x** [comment]
I have been running my bot for the last 3days without issues with the fix coming https://github.com/timgrossmann/InstaPy/pull/4696

Here are my stats for the last 24h:

![image](https://user-images.githubusercontent.com/893837/61971040-51b61a00-afde-11e9-9714-422449fab088.png)

just wait for new release guys 👍

**Comment by andifds** [comment]
Hey nice data graphics, how did you get them?

Will check the update and try

**Comment by VNRARA** [comment]
Disable headless (after updating chromedriver)
Disable cookie like said before
Enable random_user_agent 
add the chromium flags like said before

test by liking in chrome driver, refresh and see if the like sticks

**Comment by bradwalls** [comment]
@VNRARA I am unable to enable random_user_agent it is throwing back unexpected argument?

**Comment by VNRARA** [comment]
> @VNRARA I am unable to enable random_user_agent it is throwing back unexpected argument?

https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#get-a-random-useragent

Should work fine if done according to documentation.

**Comment by bradwalls** [comment]
> https://github.com/timgrossmann/InstaPy/blob/master/DOCUMENTATION.md#get-a-random-useragent
> Should work fine if done according to documentation.

I have, see the tail below @VNRARA - I've removed my pw

```
pi@raspberrypi:~/scripts $ python3 new3.py
Traceback (most recent call last):
  File "new3.py", line 6, in <module>
    session = InstaPy(username='Bradscanvas', password='xxxx', random_user_agent=True, headless_browser=False)
TypeError: __init__() got an unexpected keyword argument 'random_user_agent'
```

**Comment by VNRARA** [comment]
Looks like you need to update instaPy. Mine works just fine.. bu I've updated twice theses last couple of weeks.

**Comment by bradwalls** [comment]
updated and same issue @VNRARA

**Comment by andreescocard** [comment]
Disable headless (after updating chromedriver) - using nogui=True, chromedriver in version 2.37, when using headless_browser=False, chrome don't start
Disable cookie like said before - disabled cookie commenting browser.add_cookie(cookie) line, removed profile on logs folder (with the cookie)
Enable random_user_agent - included  random_user_agent = True on session line
add the chromium flags like said before - added

Updated Instapy, same problem :(

**Comment by Good-Kat** [comment]
updated InstaPy today. Still can't like and follow.
unix server. headless mode.

-------- WARNING! Image was NOT liked! You are have a BLOCK on likes!
WARNING [2019-08-01 14:33:29] [*********]  Phew! Last follow is not verified.	~'*********' might be temporarily blocked from following

**Comment by bjspi** [comment]
Strange thing is for me it still works with my old 0.4.4 version after editing the Chrome config as given above. I'm a bit surprised

**Comment by VNRARA** [comment]
Random user agent seems to be removed suddenly.. Idk 
I keep getting blocks again as well.

**Comment by bjspi** [comment]
> Strange thing is for me it still works with my old 0.4.4 version after editing the Chrome config as given above. I'm a bit surprised

Okay, since today it also stopped working for me (still using 0.4.4) even after deleting the cookie file etc ... Dont know what to do tbh

**Comment by bjspi** [comment]
Is it fixed for anyone who uses 0.6.0 release? or 0.5.9?

**Comment by PEtE-r0ck** [comment]
> 
> 
> I have been running my bot for the last 3days without issues with the fix coming #4696
> 
> Here are my stats for the last 24h:
> 
> ![image](https://user-images.githubusercontent.com/893837/61971040-51b61a00-afde-11e9-9714-422449fab088.png)
> 
> just wait for new release guys 👍

@iam4x nice visualisation to see bot performance over time. can you hint me towards how you did that?

**Comment by Dimensionsofahimsa** [comment]
> I edited the login_util.py file and commented out the line below:
> browser.add_cookie(cookie)
> 
> This worked for me for about 3 minutes and then I got blocked again :(.

> I edited the login_util.py file and commented out the line below:
> browser.add_cookie(cookie)
> 
> I did the same and removed cookie. Still working. Around a hour or so

Somehow on my Mac, I can't see a login.util.py file, not even hidden. I'm a bit stuck here trying to fix the issue. Also, when I do headless=False, it's Firefox that launches and not Chrome. Did all this change in the latest updates?

I'm eager to find a solution where cache would be cleared automatically

**Comment by Dimensionsofahimsa** [comment]
Or it could run in private (browser) mode maybe? But I'm not sure how I'd do that

**Comment by Dimensionsofahimsa** [comment]
I just copied all of the GitHub over to my computer and changed the login.util.py file

Now it gives me

```
  File "/Users/name/InstaPy-master/instapy/login_util.py", line 26, in <module>
    browser.add_cookie(cookie)
NameError: name 'browser' is not defined
```

**Comment by mayurrawte** [comment]
any updates on this?

**Comment by Abdulsamipy** [comment]
any solution guys?

https://github.com/timgrossmann/InstaPy/issues/5358

**Comment by rogerznts** [comment]
any updates on this?

**Comment by Abdulsamipy** [comment]
Yea please delete .pkl file

**Comment by rogerznts** [comment]
Works just for a while. Is it the same with u?

**Comment by xuhig** [comment]
yes


发自我的iPhone

------------------ Original ------------------

**Comment by Mr-Hodler** [comment]
NEWS? i have the same problem

**Comment by AyouBaws** [comment]
Same problem here! I tried to delete cookies and commented this line: browser.add_cookie(cookie), but doesn't work :(

**Comment by KMLnk** [comment]
> Same problem here! I tried to delete cookies and commented this line: browser.add_cookie(cookie), but doesn't work :(


the best robot for instagram :  https://www.v-user.com/en/side-products/instagram-robot

No block action
No need to clean cookies
unrecognizable
Unique
With timely support and updates

**Comment by GabrieleAnsaldo** [comment]
So I actually found a fix if you really want to have an instagram bot. Basically instagram got very good at detecting bots so I tried to work around that. Basically I have connected my old android phone to the Raspberry (you can connect it to any computer) and I just send a bunch of adb commands to it. I wrote a little script. Its been working so well.

I guess instagram finds it hard to find bots from someone using the app itself and not the browser version.

Hit me up if you are interested in developing this project with me, there is still a lot to do to make it very efficient.

**Comment by rogerznts** [comment]
> So I actually found a fix if you really want to have an instagram bot. Basically instagram got very good at detecting bots so I tried to work around that. Basically I have connected my old android phone to the Raspberry (you can connect it to any computer) and I just send a bunch of adb commands to it. I wrote a little script. Its been working so well.
> 
> I guess instagram finds it hard to find bots from someone using the app itself and not the browser version.
> 
> Hit me up if you are interested in developing this project with me, there is still a lot to do to make it very efficient.

thats a very good idea, thanks!

**Comment by GabrieleAnsaldo** [comment]
If you still get blocked with InstaPy read this:

So I actually found a fix if you really want to have an instagram bot. Basically instagram got very good at detecting bots so I tried to work around that. Basically I have connected my old android phone to the Raspberry (you can connect it to any computer) and I just send a bunch of adb commands to it. I wrote a little script. Its been working so well.

I guess instagram finds it hard to find bots from someone using the app itself and not the browser version.

Hit me up if you are interested in developing this project with me, there is still a lot to do to make it very efficient.

**Comment by mastrolube** [comment]
Any news about that? I'm trying with selenium 4 (beta testing) and the last of instapy but it doesn't fix that :(

I'm on a raspberry 4 and on windows.. same problem and only inside the firefox with the robot in the address bar. Works fine in normal firefox and so on..
